- name: Get docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc

- name: Add docker repo (not noble)
  when: ansible_lsb['codename'] != 'noble'
  ansible.builtin.apt_repository:
    repo: deb [arch={{deb_architecture[ansible_architecture]}} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ansible_lsb['codename']}} stable
    state: present
    filename: docker

- name: Add docker repo (noble)
  when: ansible_lsb['codename'] == 'noble'
  ansible.builtin.apt_repository:
    repo: deb [arch={{deb_architecture[ansible_architecture]}} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu jammy stable
    state: present
    filename: docker

- name: Install docker
  ansible.builtin.apt:
    name:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io 
      - docker-buildx-plugin 
      - docker-compose-plugin
    update_cache: true
    state: present