# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spacex/api/telemetron/public/common/time.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.spacex/api/telemetron/public/common/time.proto\x12#SpaceX.API.Telemetron.Public.Common\"s\n\rTimestampInfo\x12@\n\x05\x65poch\x18\x01 \x01(\x0e\x32*.SpaceX.API.Telemetron.Public.Common.EpochR\x05\x65poch\x12 \n\x0bnanoseconds\x18\x02 \x01(\x03R\x0bnanoseconds*\x1a\n\x05\x45poch\x12\x08\n\x04UNIX\x10\x00\x12\x07\n\x03GPS\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spacex.api.telemetron.public.common.time_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EPOCH']._serialized_start=204
  _globals['_EPOCH']._serialized_end=230
  _globals['_TIMESTAMPINFO']._serialized_start=87
  _globals['_TIMESTAMPINFO']._serialized_end=202
# @@protoc_insertion_point(module_scope)
