# This is the base file that implements the most basic functionality
# You should not need to edit it
# IF you have created your own custom module, look at included ones (like ping.yml) to see usage
- name: Debug {{module}} experiment
  vars:
    lol:
      module: "{{module}}"
      start: "{{start | default(None)}}"
      stop: "{{stop | default(None)}}"
      period: "{{period | default(3600)}}"
      forever: "{{forever | default(False)}}"
      setup: "{{setup | default({})}}"
      config: "{{config | default({})}}"
      tags: "{{experiment_tags | default({})}}"
      stow: "{{stow | default(False)}}"
      modules: "{{modules | default(None)}}"
  ansible.builtin.debug:
    var: lol
  when: dbg is defined and dbg

- name: Start {{module}} experiment
  ansible.builtin.uri:
    url: http://127.0.0.1:6969/{{path | default('create')}}
    method: POST
    body_format: json
    body:
      module: "{{module}}"
      start: "{{start | default(None)}}"
      stop: "{{stop | default(None)}}"
      period: "{{period | default(3600)}}"
      forever: "{{forever | default(False)}}"
      setup: "{{setup | default({})}}"
      config: "{{config | default({})}}"
      tags: "{{experiment_tags | default({})}}"
      stow: "{{stow | default(False)}}"
      modules: "{{modules | default(None)}}"
    headers:
      Content-type: Application/json
      accept: application/json
    return_content: true
  when: dbg is undefined or not dbg