- import_tasks: base.yml
  vars:
    module: device
    period: 1
    fixed_tags:
      machine: "{{inventory_hostname}}"
    experiment_tags: "{{ fixed_tags | ansible.builtin.combine(tag_with | default(None))}}"