- import_tasks: base.yml
  vars:
    module: ping
    period_seconds: 5
    measurement_tags:
      machine: "{{inventory_hostname}}"
    runtime_config:
      targets:
        - '1.1.1.1'
        - '8.8.8.8'
        - 'csgate.cs.uni-sb.de'
        - '2606:4700:4700::1111'