- import_tasks: base.yml
  vars:
    module: space_weather
    period_seconds: 5
    fixed_tags:
      machine: "{{inventory_hostname}}"
    measurement_tags: "{{ fixed_tags | ansible.builtin.combine(tag_with | default(None))}}"