- import_tasks: base.yml
  vars:
    module: traceroute
    period_seconds: 15
    fixed_tags:
      machine: "{{inventory_hostname}}"
    measurement_tags: "{{ fixed_tags | ansible.builtin.combine(tag_with | default(None))}}"
    runtime_config:
      targets:
        - '1.1.1.1'
        - '8.8.8.8'
        - 'csgate.cs.uni-sb.de'
        - '2606:4700:4700::1111'