- import_tasks: base.yml
  vars:
    module: weather
    period_seconds: 1800
    fixed_tags:
      machine: "{{inventory_hostname}}"
    measurement_tags: "{{ fixed_tags | ansible.builtin.combine(tag_with | default(None))}}"
    runtime_config:
      user_agent: "starlinktools/test user@email.xyz"