- import_tasks: base.yml
  vars:
    module: weather
    #period: 1800
    fixed_tags:
      machine: "{{inventory_hostname}}"
    experiment_tags: "{{ fixed_tags | ansible.builtin.combine(tag_with | default(None))}}"
    config:
      user_agent: "Java invalid.com"