weather:
  enable: true
  lattitude: 49.2578 #North
  longtittude: 7.049 #East
  user_agent: "StarlinkXperiments/dev vopr00001@stud.uni-saarland.de" #format: appname contact

space_weather:
  enable: true

network:
  ping:
    frequency: 1 #per 1 second
    targets: 
      - '8.8.8.8'
      - '1.1.1.1'
      #- ADD_YOUR_OWN
  trace_route:
    frequency: 1 #per 15 seconds
    targets:
      - '1.1.1.1'
      #- ADD_YOUR_OWN

grpc: 
  key: ":)" #TODO
  scrape_interval: 5 #seconds

influx: 
  key: ":P" #TODO