FROM python:3.12-alpine

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY main.py ./
COPY scheduler.py ./

### TEST SPECIFIC ADDITIONS BELLOW ###
#testing framework
RUN pip install --no-cache-dir pytest
COPY tests ./tests
#no need to mount for test, jsut copy to image to make testing easier
COPY modules ./modules

CMD [ "pytest", "./tests" ]