# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spacex/api/satellites/network/ut_disablement_codes.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8spacex/api/satellites/network/ut_disablement_codes.proto\x12\x1dSpaceX.API.Satellites.Network*\xc2\x01\n\x11UtDisablementCode\x12\x11\n\rUNKNOWN_STATE\x10\x00\x12\x08\n\x04OKAY\x10\x01\x12\x15\n\x11NO_ACTIVE_ACCOUNT\x10\x02\x12 \n\x1cTOO_FAR_FROM_SERVICE_ADDRESS\x10\x03\x12\x0c\n\x08IN_OCEAN\x10\x04\x12\x13\n\x0fINVALID_COUNTRY\x10\x05\x12\x13\n\x0f\x42LOCKED_COUNTRY\x10\x06\x12\x1f\n\x1b\x44\x41TA_OVERAGE_SANDBOX_POLICY\x10\x07\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spacex.api.satellites.network.ut_disablement_codes_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_UTDISABLEMENTCODE']._serialized_start=92
  _globals['_UTDISABLEMENTCODE']._serialized_end=286
# @@protoc_insertion_point(module_scope)
