- name: Collect measurements (JSON)
  hosts: nodes
  gather_facts: false

  tasks:
  - name: Dump collections to JSON
    community.mongodb.mongodb_shell:
      mongo_cmd: mongosh
      db: starlink
      eval: "db.runCommand('listCollections')"
    register: result

  - name: dbg
    ansible.builtin.debug:
      msg: "{{item.name}}"
    with_items: "{{result.transformed_output.cursor.firstBatch}}"
    when: item.type == 'timeseries'

    #condition on item.type = timeseries
    #extract using shell 
