---
- name: Run experiments
  hosts: nodes
  gather_facts: false

  vars:
    stop_time: "FRI, 12 JUN 2024 07:25:00 GMT"
    # Dynamic tag that will also be present in the resulting metadata for all experiments
    # alongside static tags defined in the respective fragments
    tag_with:
      test: Hi!

  tasks:
    - import_tasks: fragments/jobs/ip.yml
      vars:
        #only available for the ip experiment
        karel: VAT
    - import_tasks: fragments/jobs/ping.yml
    - import_tasks: fragments/jobs/space_weather.yml
    - import_tasks: fragments/jobs/install.yml
      vars:
        modules_to_install:
          - numpy
