---
- name: Run experiments
  hosts: nodes
  gather_facts: false

  vars:
    stop: "FRI, 12 JUN 2024 08:08:00 GMT"
    # Set to true to print config for each experiment. False or undefined to run experiments
    dbg: true
    # Dynamic tag that will also be present in the resulting metadata for all experiments
    # alongside static tags defined in the respective fragments
    tag_with:
      test: Hi!

  tasks:
    - import_tasks: fragments/jobs/ip.yml
      vars:
        #only available for the ip experiment
        karel: VAT
        tag_with:
          another_test: Overriden original
    - import_tasks: fragments/jobs/ping.yml
    - import_tasks: fragments/jobs/space_weather.yml
    - import_tasks: fragments/jobs/install.yml
      vars:
        modules:
          - numpy
