---
- name: Setup test node
  hosts: nodes
  become: true

  vars:
    deb_architecture: { 
      "armv6l": "armhf", 
      "armv7l": "armhf", 
      "aarch64": "arm64", 
      "x86_64": "amd64", 
      "i386": "i386" 
    }

  tasks:
  - import_tasks: fragments/tasks/install_docker.yml

  - import_tasks: fragments/tasks/install_mongo_util.yml

  - name: Configure docker
    ansible.builtin.template:
      src: templates/docker.j2
      dest: /etc/docker/daemon.json
    register: docker_conf

  - name: Restart docker
    ansible.builtin.service:
      name: docker
      state: restarted
    when: docker_conf['changed']


  - import_tasks: fragments/tasks/deploy_modules.yml

  - name: Copy docker compose
    become: false
    ansible.builtin.copy:
      src: '{{playbook_dir}}/../docker-compose.yml'
      dest: ~/starlinktool/docker-compose.yml
      mode: preserve

  - import_tasks: fragments/tasks/deploy_image.yml